sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t matteofiameni/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true matteofiameni/docker-react npm run test # https://create-react-app.dev/docs/running-tests

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-310045707875" # is created automatically when u create environment
  bucket_path: "docker-react" # it's the same name of ur application
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


# http://dockerreact-env.eba-gd3g44qk.us-east-2.elasticbeanstalk.com/