version: '3'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules   # don't map node_modules into container for don't override it
      - .:/app              # map all files that stay in fronted into /app container folder
      
    stdin_open: true        # 4-1-2020 | Recently, a bug was introduced with the latest Create React App 
                            #            version that is causing the React app to exit when starting with Docker Compose.

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    stdin_open: true
    command: ["npm", "test"]
